# Generated by Django 4.2.26 on 2025-11-13 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estimation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(default='Mi Estimación', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('input_m2_terreno', models.FloatField()),
                ('input_cantidad_personas', models.IntegerField()),
                ('input_orientacion', models.IntegerField()),
                ('input_forma_terreno', models.CharField(max_length=50)),
                ('result_cantidad_dormitorio', models.IntegerField()),
                ('result_cantidad_bano', models.IntegerField()),
                ('result_m2_cocina', models.FloatField()),
                ('result_m2_estar_comedor', models.FloatField()),
                ('result_m2_dormitorios_total', models.FloatField()),
                ('result_m2_banos_total', models.FloatField()),
                ('result_costo_estimado', models.FloatField()),
                ('result_tiempo_meses', models.FloatField()),
                ('result_layout_key', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
